site_name: ProgramaciÃ³n
nav:
    - ğŸ”¥ Inicio: index.md
    - ğŸ“– Leer y Entender CÃ³digo: ud0/1leer-entender-java.md
    - ğŸ’¾ Elementos de un programa informÃ¡tico: 
      - ğŸ’¾ Programa y lenguajes de programaciÃ³n: ud1/1elementos.md
      - ğŸ’¾ El lenguaje Java:
        - Conceptos bÃ¡sicos del lenguaje: ud1/121conceptosbasicos.md
        - Setup: ud1/122setup.md
        - Proyecto Hola Mundo: ud1/123holamundo.md
      - ğŸ’¾ Variables, sentencias y paquetes:
        - Variables: ud1/131variables.md
        - Sentencias y paquetes: ud1/132sentencias.md
      - ğŸ’¾ Tipos de datos: 
        - Datos primitivos: ud1/14datatypejava.md
        - Datos no primitivos: ud1/142noprimitive.md
        - String: ud1/143string.md
      - ğŸ’¾ Operadores y expresiones: ud1/15operators.md
      - ğŸ’¾ Comentarios en Java: ud1/16comments.md
      - ğŸ’¾ Constantes y literales: ud1/17constantesliterales.md
      - ğŸ’¾ Entrada y salida de informaciÃ³n por consola: ud1/18inputoutputconsole.md
      - ğŸ’¾ IntroducciÃ³n a la programaciÃ³n orientada a objetos: ud1/19poo.md
    - ğŸ–²ï¸ Estructuras bÃ¡sicas de control:
      - ğŸ–²ï¸ Estructuras de selecciÃ³n: 
        - If Statement: ud2/1seleccion.md
        - Expresiones booleanas: ud2/11booleanexpressions.md
        - Switch Statement: ud2/2switch.md
      - ğŸ–²ï¸ Estructuras de repeticiÃ³n:
        - Bucle while: ud2/22while.md
        - Bucle do while: ud2/22dowhile.md
        - Bucles while con if: ud2/22whileif.md
        - Bucle for: ud2/22for.md
        - Bucles anidados: ud2/22nestedloop.md
        - Principios del diseÃ±o de bucles: ud2/22principlesloop.md
      - ğŸ–²ï¸ Estructuras de salto:
        - Sentencias break y continue: ud2/23breakcontinue.md
      - ğŸ–²ï¸ Control de excepciones: ud2/24exceptions.md
      - ğŸ–²ï¸ Prueba y depuraciÃ³n de aplicaciones: ud2/25fallos.md
      - ğŸ–²ï¸ IntroducciÃ³n a los mÃ©todos en Java: ud2/26methods.md 
    - â™¾ï¸ Recursividad: ud3/6recursion.md
    - ğŸŒ ProgramaciÃ³n orientada a objetos POO:
      - ğŸŒ Clases en Java: ud3/1metodoclase.md
      - ğŸŒ Constructores y destructores: ud3/2constructor.md
      - ğŸŒ MÃ©todos y sobrecarga de mÃ©todos: ud3/3sobrecargametodos.md
      - ğŸŒ Paso de parÃ¡metros por valor y referencia: ud3/4referencevalue.md
      - ğŸŒ Variables, mÃ©todos y clases estÃ¡ticas: ud3/5static.md
      - ğŸŒ Null value: ud3/7nullvalue.md
      - ğŸŒ POJO, Record: ud3/8pojo.md
    - ğŸ“… Arrays:
      - ğŸ“… IntroducciÃ³n: ud4/1arrays.md
      - ğŸ“… Algoritmos Ãºtiles en arrays: ud4/2usefularrays.md
      - ğŸ“… Tipos de referencia y tipos de valor: ud4/3referencetypearrays.md
      - ğŸ“… Array de objetos: ud4/4arrayobjects.md
      - ğŸ“… Algoritmos de ordenaciÃ³n: ud4/5sortarrays.md
      - ğŸ“… Algoritmos de bÃºsqueda: ud4/6searcharrays.md
      - ğŸ“… Arrays multidimensionales: ud4/7twodimensionarray.md
    - ğŸ“± .NET MAUI:
      - ğŸ“± IntroducciÃ³n a MAUI: ud6/1introduccion-maui.md
      - ğŸ“± APIs Nativas: ud6/2apis-nativas.md
      - ğŸ“± Layouts y Controles: ud7/1layouts-controles.md
      - ğŸ“± NavegaciÃ³n y Binding: ud8/1navegacion-binding.md
      - ğŸ“± PublicaciÃ³n de Apps: ud7/2publicacion-apps.md
    - ğŸ”§ Otros Frameworks:
      - ğŸ”§ AvaloniaUI y Alternativas: ud9/1otros-frameworks.md

    - ğŸ”£ Atajos de teclado para IntelliJ: shortcuts.md
    - â¤ï¸â€ğŸ”¥ About me : about.md
theme:
  name: material
  language: es
  custom_dir: overrides
  #logo: assets/logo.png
  
  palette:
    - scheme: default
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate
      primary: teal
      accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo dÃ­a
  
  extra:
    #generator: false
  
  copyright: Copyright &copy; 2021 - Patricia MartÃ­
  
  features:
    - content.code.annotate
    - navitagion.tabs
    #- navigation.sections
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

extra:  
  analytics:
    provider: google
    property: G-FTWMZYNBPC